MOV SI,1100H  ; PUT VALUE: 78,45,98,85
MOV CL,00H
MOV AX,[SI]
MOV BX,[SI+2]
ADD AL,BL  ;ADDITION RESULT STORED IN AL=10
DAA  ;10 BCD NUMBER IS= 76
MOV DL,AL
MOV AL,AH
ADC AL,BH ;ADDITION RESULT STORED IN AL= CB
DAA ;BCD NUMBER= 31
MOV DH,AL
JNC jump
INC CL
jump:
MOV [SI+4],DX
MOV [SI+6],CL
HLT
